#!/usr/bin/env bash
# Register and start a Gitea Actions runner (act_runner) for gitea.elpatron.me
#
# Prerequisites: Docker, access to Gitea as admin
#
# 1. In Gitea: Site Administration → Actions → Runners → Create new Runner
#    (or: Repo → Settings → Actions → Runners)
#    Copy the registration token.
#
# 2. Run:
#      GITEA_RUNNER_TOKEN='paste-token-here' bash scripts/setup-gitea-runner.sh
#
# 3. Verify: Gitea → Administration → Actions → Runners → Status "Online"
#    Then re-run: Actions → Deploy (or "Runner smoke test")
#
# WireGuard deploys need /dev/net/tun inside job containers. This script writes
# a runner config with NET_ADMIN + TUN before registration when missing.
set -euo pipefail

GITEA_URL="${GITEA_URL:-https://gitea.elpatron.me}"
RUNNER_NAME="${GITEA_RUNNER_NAME:-linux-docker-$(hostname -s)}"
RUNNER_LABELS="${GITEA_RUNNER_LABELS:-ubuntu-latest:docker://catthehacker/ubuntu:act-22.04,ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04}"
DATA_DIR="${GITEA_RUNNER_DATA:-$HOME/.local/gitea-act-runner}"
CONTAINER_NAME="${GITEA_RUNNER_CONTAINER:-gitea-act-runner}"
CONFIG_FILE="$DATA_DIR/config.yaml"

if [[ -z "${GITEA_RUNNER_TOKEN:-}" ]]; then
  echo "ERROR: Set GITEA_RUNNER_TOKEN (from Gitea → Administration → Actions → Runners)"
  echo ""
  echo "Example:"
  echo "  GITEA_RUNNER_TOKEN='...' bash scripts/setup-gitea-runner.sh"
  exit 1
fi

mkdir -p "$DATA_DIR"

if [[ ! -f "$CONFIG_FILE" ]]; then
  echo "==> Writing runner config with WireGuard-capable job containers"
  cat > "$CONFIG_FILE" <<'EOF'
# Generated by scripts/setup-gitea-runner.sh — allows WireGuard in deploy jobs.
log:
  level: info

runner:
  capacity: 1
  timeout: 3h

container:
  # Job containers need TUN + NET_ADMIN for scripts/deploy-ci.sh (WireGuard).
  privileged: false
  options: "--cap-add=NET_ADMIN --device=/dev/net/tun"
  valid_volumes: []
EOF
fi

if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
  echo "==> Stopping existing container $CONTAINER_NAME"
  docker rm -f "$CONTAINER_NAME" >/dev/null
fi

echo "==> Starting act_runner"
echo "    Gitea:  $GITEA_URL"
echo "    Name:   $RUNNER_NAME"
echo "    Labels: $RUNNER_LABELS"
echo "    Data:   $DATA_DIR"
echo "    Config: $CONFIG_FILE"

docker run -d \
  --name "$CONTAINER_NAME" \
  --restart unless-stopped \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$DATA_DIR:/data" \
  -e CONFIG_FILE=/data/config.yaml \
  -e GITEA_INSTANCE_URL="$GITEA_URL" \
  -e GITEA_RUNNER_REGISTRATION_TOKEN="$GITEA_RUNNER_TOKEN" \
  -e GITEA_RUNNER_NAME="$RUNNER_NAME" \
  -e GITEA_RUNNER_LABELS="$RUNNER_LABELS" \
  gitea/act_runner:latest

echo ""
echo "==> Logs (Ctrl+C to stop watching):"
sleep 2
docker logs -f "$CONTAINER_NAME"
